# Generated by Django 3.1.1 on 2020-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201003_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='catogory',
            field=models.CharField(default='', max_length=100),
        ),
    ]
